
export const phonelogs = [
  {
    contactName: 'Sam Cookes',
    callTime: '8:45pm',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: true,
    inform: true,
  },
  {
    contactName: 'Brandon Kells',
    callTime: 'Yesterday',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Need To Call',
    urgent: true,
    inform: true,
  },
  {
    contactName: 'Joanie Funk',
    callTime: 'Yesterday',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Left A Word',
    urgent: false,
    inform: true,
  },
  {
    contactName: 'Leonardo Nightly',
    callTime: 'Mar 28',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Scheduled',
    urgent: true,
    inform: true,
  },
  {
    contactName: 'Sam Cookes',
    callTime: 'Mar 28',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: true,
    inform: true,
  },
  {
    contactName: 'Joanie Funk',
    callTime: 'Mar 25',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem facilis fuga iure laboriosam maxime minima nemo porro repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: false,
    inform: true,
  },
  {
    contactName: 'Joanie Funk',
    callTime: 'Mar 25',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem facilis fuga iure laboriosam maxime minima nemo porro repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: false,
    inform: true,
  },
  {
    contactName: 'Leonardo Nightly',
    callTime: 'Mar 28',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Scheduled',
    urgent: true,
    inform: true,
  },
  {
    contactName: 'Leonardo Nightly',
    callTime: 'Mar 28',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Scheduled',
    urgent: true,
    inform: true,
  },
  {
    contactName: 'Sam Cookes',
    callTime: '8:45pm',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: true,
    inform: true,
  },
  {
    contactName: 'Brandon Kells',
    callTime: 'Yesterday',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Need To Call',
    urgent: true,
    inform: true,
  },
];
