
export const phonelogs = [
  {
    id: 1,
    contactName: 'Sam Cookes',
    callTime: '8:45pm',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: true,
    inform: true,
  },
  {
    id: 2,
    contactName: 'Brandon Kells',
    callTime: 'Yesterday',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Need To Call',
    urgent: true,
    inform: true,
  },
  {
    id: 3,
    contactName: 'Joanie Funk',
    callTime: 'Yesterday',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Left A Word',
    urgent: false,
    inform: true,
  },
  {
    id: 4,
    contactName: 'Leonardo Nightly',
    callTime: 'Mar 28',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Scheduled',
    urgent: true,
    inform: true,
  },
  {
    id: 5,
    contactName: 'Sam Cookes',
    callTime: 'Mar 28',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: true,
    inform: true,
  },
  {
    id: 6,
    contactName: 'Joanie Funk',
    callTime: 'Mar 25',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem facilis fuga iure laboriosam maxime minima nemo porro repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: false,
    inform: true,
  },
  {
    id: 7,
    contactName: 'Joanie Funk',
    callTime: 'Mar 25',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem facilis fuga iure laboriosam maxime minima nemo porro repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: false,
    inform: true,
  },
  {
    id: 8,
    contactName: 'Leonardo Nightly',
    callTime: 'Mar 28',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem repellat.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Scheduled',
    urgent: true,
    inform: true,
  },
  {
    id: 9,
    contactName: 'Leonardo Nightly',
    callTime: 'Mar 28',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Scheduled',
    urgent: true,
    inform: true,
  },
  {
    id: 10,
    contactName: 'Sam Cookes',
    callTime: '8:45pm',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Will Call Back',
    urgent: true,
    inform: true,
  },
  {
    id: 11,
    contactName: 'Brandon Kells',
    callTime: 'Yesterday',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur ducimus exercitationem.',
    phoneNumber: '+1 678 642 4214',
    callStatus: 'Need To Call',
    urgent: true,
    inform: true,
  },
];

export const users = [
  {
    userName: 'Marcelle Quigley',
  },
  {
    userName: 'Senior Pomador',
  },
  {
    userName: 'Brandon Lays',
  },
  {
    userName: 'Keeper of the Light',
  },
  {
    userName: 'Brain Machine',
  },
  {
    userName: 'Ivan Grozniy',
  },
  {
    userName: 'Karl III',
  },
  {
    userName: 'Big Bad Wolf',
  },
];
